# view dataset files

In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [3]:
%matplotlib inline

# loading data 

In [4]:
selected_cells = 'fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count'.split(',')
selected_cells

['fare_amount',
 'pickup_datetime',
 'pickup_longitude',
 'pickup_latitude',
 'dropoff_longitude',
 'dropoff_latitude',
 'passenger_count']

In [5]:
data_types = {
    'fare_amount':'float32',
    'pickup_datetime':'float32',
  'pickup_longitude':'float32',
  'pickup_latitude':'float32',
  'dropoff_longitude':'float32',
  'dropoff_latitude':'float32',
  'passenger_count':'uint8'
}

In [6]:
# sample_frac = 0.01

In [7]:
# import random

In [8]:
# def skip(index):
#     if index ==0:
#         return False
#     return random.random() > sample_frac

In [9]:
# random.seed(42)

In [10]:
# data_train = pd.read_csv("train.csv",
#                          usecols=selected_cells,
#                          skiprows=lambda x : skip(x),
#                          dtype=data_types,
#                          parse_dates=['pickup_datetime'])

In [11]:
data_train = pd.read_csv("req_1_train.csv",parse_dates=['pickup_datetime'])

In [12]:
data_train.head()

fare_amount           pickup_datetime  pickup_longitude  pickup_latitude  \
0         13.5 2013-07-06 17:18:00+00:00         -73.95065        40.783283   
1          9.0 2015-02-15 22:41:32+00:00         -74.00345        40.733100   
2          5.7 2011-12-13 05:56:00+00:00         -73.99049        40.755980   
3          5.3 2012-04-02 08:02:16+00:00         -73.94800        40.778540   
4         13.0 2013-11-07 10:19:35+00:00         -73.98580        40.777477   

   dropoff_longitude  dropoff_latitude  passenger_count  
0         -73.984370         40.769802                1  
1         -74.008000         40.707214                1  
2         -73.974205         40.754210                4  
3         -73.958565         40.778484                2  
4         -73.987410         40.754368                1

In [13]:
d = pd.read_csv('test.csv')

In [14]:
d

key          pickup_datetime  pickup_longitude  \
0     2015-01-27 13:08:24.0000002  2015-01-27 13:08:24 UTC        -73.973320   
1     2015-01-27 13:08:24.0000003  2015-01-27 13:08:24 UTC        -73.986862   
2     2011-10-08 11:53:44.0000002  2011-10-08 11:53:44 UTC        -73.982524   
3     2012-12-01 21:12:12.0000002  2012-12-01 21:12:12 UTC        -73.981160   
4     2012-12-01 21:12:12.0000003  2012-12-01 21:12:12 UTC        -73.966046   
...                           ...                      ...               ...   
9909  2015-05-10 12:37:51.0000002  2015-05-10 12:37:51 UTC        -73.968124   
9910  2015-01-12 17:05:51.0000001  2015-01-12 17:05:51 UTC        -73.945511   
9911  2015-04-19 20:44:15.0000001  2015-04-19 20:44:15 UTC        -73.991600   
9912  2015-01-31 01:05:19.0000005  2015-01-31 01:05:19 UTC        -73.985573   
9913  2015-01-18 14:06:23.0000006  2015-01-18 14:06:23 UTC        -73.988022   

      pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  
0           40.763805         -73.981430         40.743835                1  
1           40.719383         -73.998886         40.739201                1  
2           40.751260         -73.979654         40.746139                1  
3           40.767807         -73.990448         40.751635                1  
4           40.789775         -73.988565         40.744427                1  
...               ...                ...               ...              ...  
9909        40.796997         -73.955643         40.780388                6  
9910        40.803600         -73.960213         40.776371                6  
9911        40.726608         -73.789742         40.647011                6  
9912        40.735432         -73.939178         40.801731                6  
9913        40.754070         -74.000282         40.759220                6  

[9914 rows x 7 columns]

In [15]:
d.shape

(9914, 7)

In [16]:
data_types_test = {
    'fare_amount':'float32',
  'pickup_longitude':'float32',
  'pickup_latitude':'float32',
  'dropoff_longitude':'float32',
  'dropoff_latitude':'float32',
  'passenger_count':'uint8'
}

In [17]:
data_test = pd.read_csv("test.csv",dtype=data_types_test,parse_dates=['pickup_datetime'])

In [18]:
data_test

key           pickup_datetime  pickup_longitude  \
0     2015-01-27 13:08:24.0000002 2015-01-27 13:08:24+00:00        -73.973320   
1     2015-01-27 13:08:24.0000003 2015-01-27 13:08:24+00:00        -73.986862   
2     2011-10-08 11:53:44.0000002 2011-10-08 11:53:44+00:00        -73.982521   
3     2012-12-01 21:12:12.0000002 2012-12-01 21:12:12+00:00        -73.981163   
4     2012-12-01 21:12:12.0000003 2012-12-01 21:12:12+00:00        -73.966049   
...                           ...                       ...               ...   
9909  2015-05-10 12:37:51.0000002 2015-05-10 12:37:51+00:00        -73.968124   
9910  2015-01-12 17:05:51.0000001 2015-01-12 17:05:51+00:00        -73.945511   
9911  2015-04-19 20:44:15.0000001 2015-04-19 20:44:15+00:00        -73.991600   
9912  2015-01-31 01:05:19.0000005 2015-01-31 01:05:19+00:00        -73.985573   
9913  2015-01-18 14:06:23.0000006 2015-01-18 14:06:23+00:00        -73.988022   

      pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  
0           40.763805         -73.981430         40.743835                1  
1           40.719383         -73.998886         40.739201                1  
2           40.751259         -73.979652         40.746140                1  
3           40.767807         -73.990448         40.751637                1  
4           40.789776         -73.988564         40.744427                1  
...               ...                ...               ...              ...  
9909        40.796997         -73.955643         40.780388                6  
9910        40.803600         -73.960213         40.776371                6  
9911        40.726608         -73.789742         40.647011                6  
9912        40.735432         -73.939178         40.801731                6  
9913        40.754070         -74.000282         40.759220                6  

[9914 rows x 7 columns]

# exploring the data

In [19]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 553888 entries, 0 to 553887
Data columns (total 7 columns):
 #   Column             Non-Null Count   Dtype              
---  ------             --------------   -----              
 0   fare_amount        553888 non-null  float64            
 1   pickup_datetime    553888 non-null  datetime64[ns, UTC]
 2   pickup_longitude   553888 non-null  float64            
 3   pickup_latitude    553888 non-null  float64            
 4   dropoff_longitude  553884 non-null  float64            
 5   dropoff_latitude   553884 non-null  float64            
 6   passenger_count    553888 non-null  int64              
dtypes: datetime64[ns, UTC](1), float64(5), int64(1)
memory usage: 29.6 MB


In [20]:
data_train.describe()

fare_amount  pickup_longitude  pickup_latitude  dropoff_longitude  \
count  553888.000000     553888.000000    553888.000000      553884.000000   
mean       11.325466        -72.539418        39.910143         -72.531035   
std         9.752500         15.121063         8.770774          13.238080   
min       -52.000000      -3442.059600     -2145.906000       -3370.710400   
25%         6.000000        -73.992080        40.734910         -73.991380   
50%         8.500000        -73.981804        40.752660         -73.980110   
75%        12.500000        -73.967090        40.767143         -73.963680   
max       444.440000         40.813038      3334.677700          40.827824   

       dropoff_latitude  passenger_count  
count     553884.000000    553888.000000  
mean          39.897806         1.687171  
std            8.959665         1.339930  
min        -2530.357400         0.000000  
25%           40.733974         1.000000  
50%           40.753166         1.000000  
75%           40.768140         2.000000  
max          458.650000       208.000000

In [21]:
data_train['pickup_datetime'].min(), data_train['pickup_datetime'].max()

(Timestamp('2009-01-01 00:04:54+0000', tz='UTC'),
 Timestamp('2015-06-30 23:56:42+0000', tz='UTC'))

In [22]:
data_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9914 entries, 0 to 9913
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype              
---  ------             --------------  -----              
 0   key                9914 non-null   object             
 1   pickup_datetime    9914 non-null   datetime64[ns, UTC]
 2   pickup_longitude   9914 non-null   float32            
 3   pickup_latitude    9914 non-null   float32            
 4   dropoff_longitude  9914 non-null   float32            
 5   dropoff_latitude   9914 non-null   float32            
 6   passenger_count    9914 non-null   uint8              
dtypes: datetime64[ns, UTC](1), float32(4), object(1), uint8(1)
memory usage: 319.6+ KB


In [23]:
data_test.describe()

pickup_longitude  pickup_latitude  dropoff_longitude  dropoff_latitude  \
count       9914.000000      9914.000000        9914.000000       9914.000000   
mean         -73.976181        40.750954         -73.974945         40.751553   
std            0.042799         0.033542           0.039093          0.035436   
min          -74.252190        40.573143         -74.263245         40.568974   
25%          -73.992500        40.736125         -73.991249         40.735253   
50%          -73.982327        40.753052         -73.980015         40.754065   
75%          -73.968012        40.767113         -73.964062         40.768757   
max          -72.986534        41.709557         -72.990967         41.696682   

       passenger_count  
count      9914.000000  
mean          1.671273  
std           1.278747  
min           1.000000  
25%           1.000000  
50%           1.000000  
75%           2.000000  
max           6.000000

In [24]:
data_test['pickup_datetime'].min(),data_test['pickup_datetime'].max()

(Timestamp('2009-01-01 11:04:24+0000', tz='UTC'),
 Timestamp('2015-06-30 20:03:50+0000', tz='UTC'))

In [25]:
data_test['pickup_datetime'].dtype

datetime64[ns, UTC]

# splitting the data as training set and validation set

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
train_df,val_df = train_test_split(data_train,test_size=0.2,random_state=42)

In [28]:
len(train_df),len(val_df)

(443110, 110778)

In [29]:
train_df

fare_amount           pickup_datetime  pickup_longitude  \
159962         10.0 2012-12-19 19:08:00+00:00        -73.980760   
239519          5.7 2009-06-15 20:20:00+00:00        -73.984960   
55333           8.0 2013-07-02 09:39:00+00:00        -73.958760   
21154          19.3 2011-01-11 19:17:42+00:00        -73.959236   
257163          6.5 2014-03-06 18:14:00+00:00        -74.010980   
...             ...                       ...               ...   
110268          9.7 2011-10-21 13:43:00+00:00        -73.987150   
259178          4.5 2011-01-15 07:27:50+00:00        -73.991050   
365838          5.0 2015-06-15 07:51:32+00:00        -73.971390   
131932          6.9 2012-01-24 19:01:00+00:00        -73.975750   
121958          7.3 2009-10-23 17:44:29+00:00        -73.959360   

        pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  
159962        40.769620         -73.959650         40.776943                1  
239519        40.751000         -73.990456         40.760868                2  
55333         40.780870         -73.980430         40.773212                1  
21154         40.763165         -74.010830         40.718720                1  
257163        40.716526         -74.007790         40.732048                1  
...                 ...                ...               ...              ...  
110268        40.740574         -74.001510         40.720050                2  
259178        40.750957         -73.983090         40.756523                1  
365838        40.766884         -73.977684         40.758200                1  
131932        40.751260         -73.999405         40.761060                1  
121958        40.771584         -73.967080         40.758846                1  

[443110 rows x 7 columns]

In [30]:
train_df['pickup_datetime'].dtype

datetime64[ns, UTC]

In [31]:
# dropping the nan values(tho no nan is presenrt here)

In [32]:
train_df = train_df.dropna()
val_df = val_df.dropna()

In [33]:
len(train_df),len(val_df)

(443107, 110777)

# extracting input and output

In [34]:
# for training set

In [35]:
train_df.columns

Index(['fare_amount', 'pickup_datetime', 'pickup_longitude', 'pickup_latitude',
       'dropoff_longitude', 'dropoff_latitude', 'passenger_count'],
      dtype='object')

In [36]:
input_cols = ['pickup_longitude', 'pickup_latitude','dropoff_longitude', 'dropoff_latitude', 'passenger_count']
target_col = ['fare_amount']

In [37]:
train_inputs = train_df[input_cols]
train_targets = train_df[target_col]

In [38]:
train_inputs.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 443107 entries, 159962 to 121958
Data columns (total 5 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   pickup_longitude   443107 non-null  float64
 1   pickup_latitude    443107 non-null  float64
 2   dropoff_longitude  443107 non-null  float64
 3   dropoff_latitude   443107 non-null  float64
 4   passenger_count    443107 non-null  int64  
dtypes: float64(4), int64(1)
memory usage: 20.3 MB


In [39]:
train_targets.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 443107 entries, 159962 to 121958
Data columns (total 1 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   fare_amount  443107 non-null  float64
dtypes: float64(1)
memory usage: 6.8 MB


In [40]:
# for validation set

In [41]:
val_inputs = val_df[input_cols]
val_targets = val_df[target_col]

In [42]:
# for test set

In [43]:
test_inputs = data_test[input_cols]

# training with hardcoded and baseline model

# hardcoded model

In [44]:
class meanregressor():
    def fit(self,inputs,target):
        self.mean = target.mean()
    def avg(self):
        return self.mean
        
    def predict(self,inputs):
        return np.full(inputs.shape[0],self.mean)

In [45]:
mean_model = meanregressor()

In [46]:
mean_model.fit(train_inputs,train_targets)

In [47]:
mean_model.avg()

fare_amount    11.327012
dtype: float64

In [48]:
train_pred = mean_model.predict(train_inputs)

In [49]:
train_pred

array([11.32701226, 11.32701226, 11.32701226, ..., 11.32701226,
       11.32701226, 11.32701226])

In [50]:
val_pred = mean_model.predict(val_inputs)

In [51]:
val_pred

array([11.32701226, 11.32701226, 11.32701226, ..., 11.32701226,
       11.32701226, 11.32701226])

In [52]:
train_targets

fare_amount
159962         10.0
239519          5.7
55333           8.0
21154          19.3
257163          6.5
...             ...
110268          9.7
259178          4.5
365838          5.0
131932          6.9
121958          7.3

[443107 rows x 1 columns]

In [53]:
# mean squared error(RMSE)

In [54]:
from sklearn.metrics import mean_squared_error

In [55]:
def rmse(targets,preds):
    return mean_squared_error(targets,preds,squared=False)

In [56]:
train_rmse = rmse(train_targets,train_pred)

In [57]:
train_rmse

9.749803737036641

In [58]:
val_rmse = rmse(val_targets,val_pred)

In [59]:
val_rmse

9.763386431234919

# Baseline model

In [60]:
#linear Regression

In [61]:
from sklearn.linear_model import LinearRegression

In [62]:
linear_model = LinearRegression()

In [63]:
linear_model.fit(train_inputs,train_targets)

LinearRegression()

In [64]:
train_pred = linear_model.predict(train_inputs)

In [65]:
train_pred

array([[11.24489171],
       [11.34532071],
       [11.24513369],
       ...,
       [11.245132  ],
       [11.24487783],
       [11.24525045]])

In [66]:
train_rmse = rmse(train_targets,train_pred)

In [67]:
train_rmse

9.748035038134221

In [68]:
val_pred = linear_model.predict(val_inputs)

In [69]:
val_pred

array([[11.34547536],
       [11.24451864],
       [11.24501106],
       ...,
       [11.24554204],
       [11.98187264],
       [11.24472245]])

In [70]:
val_rmse = rmse(val_targets,val_pred)

In [71]:
val_rmse

9.761543498274017

In [72]:
test_inputs

pickup_longitude  pickup_latitude  dropoff_longitude  dropoff_latitude  \
0           -73.973320        40.763805         -73.981430         40.743835   
1           -73.986862        40.719383         -73.998886         40.739201   
2           -73.982521        40.751259         -73.979652         40.746140   
3           -73.981163        40.767807         -73.990448         40.751637   
4           -73.966049        40.789776         -73.988564         40.744427   
...                ...              ...                ...               ...   
9909        -73.968124        40.796997         -73.955643         40.780388   
9910        -73.945511        40.803600         -73.960213         40.776371   
9911        -73.991600        40.726608         -73.789742         40.647011   
9912        -73.985573        40.735432         -73.939178         40.801731   
9913        -73.988022        40.754070         -74.000282         40.759220   

      passenger_count  
0                   1  
1                   1  
2                   1  
3                   1  
4                   1  
...               ...  
9909                6  
9910                6  
9911                6  
9912                6  
9913                6  

[9914 rows x 5 columns]

In [73]:
test_pred = linear_model.predict(test_inputs)

In [74]:
test_pred

array([[11.24527603],
       [11.24479111],
       [11.24507439],
       ...,
       [11.74879243],
       [11.74660411],
       [11.7472437 ]])

In [75]:
sub_df = pd.read_csv('sample_submission.csv')

In [76]:
sub_df

key  fare_amount
0     2015-01-27 13:08:24.0000002        11.35
1     2015-01-27 13:08:24.0000003        11.35
2     2011-10-08 11:53:44.0000002        11.35
3     2012-12-01 21:12:12.0000002        11.35
4     2012-12-01 21:12:12.0000003        11.35
...                           ...          ...
9909  2015-05-10 12:37:51.0000002        11.35
9910  2015-01-12 17:05:51.0000001        11.35
9911  2015-04-19 20:44:15.0000001        11.35
9912  2015-01-31 01:05:19.0000005        11.35
9913  2015-01-18 14:06:23.0000006        11.35

[9914 rows x 2 columns]

In [77]:
sub_df['fare_amount']= test_pred

In [78]:
sub_df

key  fare_amount
0     2015-01-27 13:08:24.0000002    11.245276
1     2015-01-27 13:08:24.0000003    11.244791
2     2011-10-08 11:53:44.0000002    11.245074
3     2012-12-01 21:12:12.0000002    11.245157
4     2012-12-01 21:12:12.0000003    11.245556
...                           ...          ...
9909  2015-05-10 12:37:51.0000002    11.747571
9910  2015-01-12 17:05:51.0000001    11.747800
9911  2015-04-19 20:44:15.0000001    11.748792
9912  2015-01-31 01:05:19.0000005    11.746604
9913  2015-01-18 14:06:23.0000006    11.747244

[9914 rows x 2 columns]

In [79]:
sub_df.to_csv('linear_model_submission.csv',index=None)

# Reusable predict and submit function

In [80]:
def predict_and_submit(model,test_inputs,fname):
    test_pred = model.predict(test_inputs)
    sub_df = pd.read_csv('sample_submission.csv')
    sub_df['fare_amount']=test_pred
    sub_df.to_csv(fname,index = None)
    return sub_df

In [81]:
type(test_inputs)

pandas.core.frame.DataFrame

# feature engineering

In [82]:
# extract date and time
# remove outliers and invalid data
# add distance between pickup and dropoff
# add distance from landmark

In [83]:
#extract date and time

In [84]:
def add_dateparts(df,col):
    df[col+'_year']=df[col].dt.year
    df[col+'_month']=df[col].dt.month
    df[col+'_day']=df[col].dt.day
    df[col+'_weekday']=df[col].dt.weekday
    df[col+'_hour']=df[col].dt.hour

In [85]:
add_dateparts(train_df,'pickup_datetime')

<ipython-input-84-5c767b9dcae8>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col+'_year']=df[col].dt.year
<ipython-input-84-5c767b9dcae8>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col+'_month']=df[col].dt.month
<ipython-input-84-5c767b9dcae8>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexi

In [86]:
add_dateparts(val_df,'pickup_datetime')

In [87]:
add_dateparts(data_test,'pickup_datetime')

In [88]:
# distance between pickup and dropoff(haversine formula)

In [89]:
def haversine_km(long1,lat1,long2,lat2):
    """
    Calculate the great circle distance between two points 
    on the earth (specified in decimal degrees)
    """
    # convert decimal degrees to radians 
    long1, lat1, long2, lat2 = map(np.radians, [long1, lat1, long2, lat2])
    # haversine formula 
    dlong = long2 - long1 
    dlat = lat2 - lat1 
    a = np.sin(dlat/2.0)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlong/2.0)**2
    c = 2 * np.arcsin(np.sqrt(a)) 
    km = 6367 * c
    return km

In [90]:
def add_distance(df):
    df['trip_distance']=haversine_km(df['pickup_longitude'],
                                     df['pickup_latitude'],
                                     df['dropoff_longitude'],
                                     df['dropoff_latitude'])

In [91]:
add_distance(train_df)
add_distance(val_df)

<ipython-input-90-ef37a6cde292>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['trip_distance']=haversine_km(df['pickup_longitude'],


In [92]:
add_distance(data_test)

In [93]:
train_df.head()

fare_amount           pickup_datetime  pickup_longitude  \
159962         10.0 2012-12-19 19:08:00+00:00        -73.980760   
239519          5.7 2009-06-15 20:20:00+00:00        -73.984960   
55333           8.0 2013-07-02 09:39:00+00:00        -73.958760   
21154          19.3 2011-01-11 19:17:42+00:00        -73.959236   
257163          6.5 2014-03-06 18:14:00+00:00        -74.010980   

        pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  \
159962        40.769620         -73.959650         40.776943                1   
239519        40.751000         -73.990456         40.760868                2   
55333         40.780870         -73.980430         40.773212                1   
21154         40.763165         -74.010830         40.718720                1   
257163        40.716526         -74.007790         40.732048                1   

        pickup_datetime_year  pickup_datetime_month  pickup_datetime_day  \
159962                  2012                     12                   19   
239519                  2009                      6                   15   
55333                   2013                      7                    2   
21154                   2011                      1                   11   
257163                  2014                      3                    6   

        pickup_datetime_weekday  pickup_datetime_hour  trip_distance  
159962                        2                    19       1.954026  
239519                        0                    20       1.190179  
55333                         1                     9       2.012331  
21154                         1                    19       6.577513  
257163                        3                    18       1.745680

In [94]:
# add distance from landmark

In [95]:
# landmarks:
#     JKF AIRPORT
#     LGA AIRPORT
#     EWR AIRPORT
#     TIMES SQUARE
#     MET MUSEUM
#     WORLD TRADE CENTER

In [96]:
jkf_longlat = -73.7781, 40.6413
lga_longlat = -73.8740, 40.7769
ewr_longlat = -74.1745, 40.6895
tme_longlat = -73.9855, 40.7580
met_longlat = -73.9632, 40.7794
wtc_longlat = -74.0099, 40.7126

In [97]:
def add_landmark_distance(df,land_name,land_longlat):
    long,lat = land_longlat
    df[land_name+'_drop_distance']=haversine_km(long,lat,df['dropoff_longitude'],df['dropoff_latitude'])

In [98]:
def add_landmarks(df):
    landmarks = [('JKF',jkf_longlat),
                 ('LGA',lga_longlat),
                ('EWR',ewr_longlat),
                ('TME',tme_longlat),
                ('MET',met_longlat),
                ('WTC',wtc_longlat)]
    for name,longlat in landmarks:
        add_landmark_distance(df,name,longlat)

In [99]:
add_landmarks(train_df)

<ipython-input-97-05172b13cb8a>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[land_name+'_drop_distance']=haversine_km(long,lat,df['dropoff_longitude'],df['dropoff_latitude'])


In [100]:
add_landmarks(val_df)

In [101]:
add_landmarks(data_test)

In [102]:
train_df.head()

fare_amount           pickup_datetime  pickup_longitude  \
159962         10.0 2012-12-19 19:08:00+00:00        -73.980760   
239519          5.7 2009-06-15 20:20:00+00:00        -73.984960   
55333           8.0 2013-07-02 09:39:00+00:00        -73.958760   
21154          19.3 2011-01-11 19:17:42+00:00        -73.959236   
257163          6.5 2014-03-06 18:14:00+00:00        -74.010980   

        pickup_latitude  dropoff_longitude  dropoff_latitude  passenger_count  \
159962        40.769620         -73.959650         40.776943                1   
239519        40.751000         -73.990456         40.760868                2   
55333         40.780870         -73.980430         40.773212                1   
21154         40.763165         -74.010830         40.718720                1   
257163        40.716526         -74.007790         40.732048                1   

        pickup_datetime_year  pickup_datetime_month  pickup_datetime_day  \
159962                  2012                     12                   19   
239519                  2009                      6                   15   
55333                   2013                      7                    2   
21154                   2011                      1                   11   
257163                  2014                      3                    6   

        pickup_datetime_weekday  pickup_datetime_hour  trip_distance  \
159962                        2                    19       1.954026   
239519                        0                    20       1.190179   
55333                         1                     9       2.012331   
21154                         1                    19       6.577513   
257163                        3                    18       1.745680   

        JKF_drop_distance  LGA_drop_distance  EWR_drop_distance  \
159962          21.472861           7.207483          20.536017   
239519          22.284619           9.961608          17.410613   
55333           22.480563           8.965750          18.804413   
21154           21.416838          13.209648          14.165163   
257163          21.824304          12.315889          14.817287   

        TME_drop_distance  MET_drop_distance  WTC_drop_distance  
159962           3.027281           0.404705           8.307964  
239519           0.524972           3.082645           5.608089  
55333            1.743461           1.604722           7.177982  
21154            4.858175           7.845204           0.684582  
257163           3.440736           6.463520           2.168455

# remove outliers and invalid data

In [103]:
data_train.describe()

fare_amount  pickup_longitude  pickup_latitude  dropoff_longitude  \
count  553888.000000     553888.000000    553888.000000      553884.000000   
mean       11.325466        -72.539418        39.910143         -72.531035   
std         9.752500         15.121063         8.770774          13.238080   
min       -52.000000      -3442.059600     -2145.906000       -3370.710400   
25%         6.000000        -73.992080        40.734910         -73.991380   
50%         8.500000        -73.981804        40.752660         -73.980110   
75%        12.500000        -73.967090        40.767143         -73.963680   
max       444.440000         40.813038      3334.677700          40.827824   

       dropoff_latitude  passenger_count  
count     553884.000000    553888.000000  
mean          39.897806         1.687171  
std            8.959665         1.339930  
min        -2530.357400         0.000000  
25%           40.733974         1.000000  
50%           40.753166         1.000000  
75%           40.768140         2.000000  
max          458.650000       208.000000

In [104]:
data_test.describe()

pickup_longitude  pickup_latitude  dropoff_longitude  dropoff_latitude  \
count       9914.000000      9914.000000        9914.000000       9914.000000   
mean         -73.976181        40.750954         -73.974945         40.751553   
std            0.042799         0.033542           0.039093          0.035436   
min          -74.252190        40.573143         -74.263245         40.568974   
25%          -73.992500        40.736125         -73.991249         40.735253   
50%          -73.982327        40.753052         -73.980015         40.754065   
75%          -73.968012        40.767113         -73.964062         40.768757   
max          -72.986534        41.709557         -72.990967         41.696682   

       passenger_count  pickup_datetime_year  pickup_datetime_month  \
count      9914.000000           9914.000000            9914.000000   
mean          1.671273           2011.815816               6.857979   
std           1.278747              1.803347               3.353272   
min           1.000000           2009.000000               1.000000   
25%           1.000000           2010.000000               4.000000   
50%           1.000000           2012.000000               7.000000   
75%           2.000000           2014.000000              10.000000   
max           6.000000           2015.000000              12.000000   

       pickup_datetime_day  pickup_datetime_weekday  pickup_datetime_hour  \
count          9914.000000              9914.000000           9914.000000   
mean             16.194170                 2.852834             13.467420   
std               8.838482                 1.994451              6.868584   
min               1.000000                 0.000000              0.000000   
25%               9.000000                 1.000000              8.000000   
50%              16.000000                 3.000000             15.000000   
75%              25.000000                 5.000000             19.000000   
max              31.000000                 6.000000             23.000000   

       trip_distance  JKF_drop_distance  LGA_drop_distance  EWR_drop_distance  \
count    9914.000000        9914.000000        9914.000000        9914.000000   
mean        3.433212          20.916758           9.675153          18.546644   
std         3.969877           3.303940           3.295646           4.035816   
min         0.000000           0.401900           0.285629           0.284680   
25%         1.297261          20.513337           8.311565          16.520517   
50%         2.215648          21.181472           9.477797          18.024350   
75%         4.043051          21.909794          10.965272          19.880536   
max        99.933281         134.497726         126.062576         149.400787   

       TME_drop_distance  MET_drop_distance  WTC_drop_distance  
count        9914.000000        9914.000000        9914.000000  
mean            3.435211           4.512908           6.037651  
std             3.996561           4.018421           4.252535  
min             0.020707           0.085747           0.040269  
25%             1.269973           2.126287           3.670107  
50%             2.570288           3.698123           5.541466  
75%             4.129103           5.922544           7.757612  
max           133.376190         130.347153         138.619492

In [105]:
# limiting the values
#     fare_amount = 1 to 500
#     longitude = -75 to -72
#     latitude = 40 to 42
#     passenger = 1 to 6

In [106]:
def remove_outliers(df):
    return df[(df['pickup_longitude']>=-75)
             & (df['pickup_longitude']<=-72)
             & (df['dropoff_longitude']>=-75)
             & (df['dropoff_longitude']<=-72)
             & (df['pickup_latitude']>=40)
             & (df['pickup_latitude']<=42)
             & (df['dropoff_latitude']>=40)
             & (df['dropoff_latitude']<=42)
             & (df['passenger_count']>=1)
             & (df['passenger_count']<=6)
             & (df['fare_amount']>=1)
             & (df['fare_amount']<=500)]

In [107]:
train_df=remove_outliers(train_df)

In [108]:
val_df = remove_outliers(val_df)

# Train and Evaluate different models

In [109]:
train_df.columns

Index(['fare_amount', 'pickup_datetime', 'pickup_longitude', 'pickup_latitude',
       'dropoff_longitude', 'dropoff_latitude', 'passenger_count',
       'pickup_datetime_year', 'pickup_datetime_month', 'pickup_datetime_day',
       'pickup_datetime_weekday', 'pickup_datetime_hour', 'trip_distance',
       'JKF_drop_distance', 'LGA_drop_distance', 'EWR_drop_distance',
       'TME_drop_distance', 'MET_drop_distance', 'WTC_drop_distance'],
      dtype='object')

In [110]:
train_inputs.columns

Index(['pickup_longitude', 'pickup_latitude', 'dropoff_longitude',
       'dropoff_latitude', 'passenger_count'],
      dtype='object')

In [111]:
input_cols = ['pickup_longitude', 'pickup_latitude',
       'dropoff_longitude', 'dropoff_latitude', 'passenger_count',
       'pickup_datetime_year', 'pickup_datetime_month', 'pickup_datetime_day',
       'pickup_datetime_weekday', 'pickup_datetime_hour', 'trip_distance',
       'JKF_drop_distance', 'LGA_drop_distance', 'EWR_drop_distance',
       'TME_drop_distance', 'MET_drop_distance', 'WTC_drop_distance']

In [112]:
target_col

['fare_amount']

In [113]:
train_inputs = train_df[input_cols]

In [114]:
train_targets = train_df[target_col]

In [115]:
train_targets

fare_amount
159962         10.0
239519          5.7
55333           8.0
21154          19.3
257163          6.5
...             ...
110268          9.7
259178          4.5
365838          5.0
131932          6.9
121958          7.3

[432166 rows x 1 columns]

In [116]:
val_inputs = val_df[input_cols]

In [117]:
val_targets = val_df[target_col]

In [118]:
test_inputs = data_test[input_cols]

In [119]:
# helper function to evaluate models

In [120]:
def evaluate(model):
    train_pred = model.predict(train_inputs)
    train_rmse = mean_squared_error(train_targets,train_pred,squared=False)
    val_pred = model.predict(val_inputs)
    val_rmse = mean_squared_error(val_targets,val_pred,squared=False)
    return train_rmse,val_rmse,train_pred,val_pred

# Ridge Regression

In [121]:
from sklearn.linear_model import Ridge

In [122]:
ridge_model = Ridge(random_state = 42,alpha= 0.9)

In [123]:
ridge_model.fit(train_inputs,train_targets)

Ridge(alpha=0.9, random_state=42)

In [124]:
evaluate(ridge_model)

(5.20897271816812,
 5.200847779718783,
 array([[ 7.25363487],
        [ 6.54336603],
        [ 8.83202592],
        ...,
        [ 8.56325779],
        [10.24139059],
        [ 6.16323898]]),
 array([[ 6.08034366],
        [11.93485118],
        [25.74308578],
        ...,
        [25.37723424],
        [14.31972944],
        [13.23108208]]))

In [125]:
# saving the predicted data

In [126]:
predict_and_submit(ridge_model,test_inputs,'ridge_model_submission.csv')

key  fare_amount
0     2015-01-27 13:08:24.0000002    10.331414
1     2015-01-27 13:08:24.0000003    11.604271
2     2011-10-08 11:53:44.0000002     5.754653
3     2012-12-01 21:12:12.0000002     9.119327
4     2012-12-01 21:12:12.0000003    14.513145
...                           ...          ...
9909  2015-05-10 12:37:51.0000002     8.381164
9910  2015-01-12 17:05:51.0000001    10.555876
9911  2015-04-19 20:44:15.0000001    47.774772
9912  2015-01-31 01:05:19.0000005    22.166441
9913  2015-01-18 14:06:23.0000006     9.429585

[9914 rows x 2 columns]

# Random Forest

In [127]:
from sklearn.ensemble import RandomForestRegressor

In [128]:
randomfor_model = RandomForestRegressor(random_state=42,n_jobs=-1, n_estimators=100,max_depth=10)

In [129]:
randomfor_model.fit(train_inputs,train_targets)

<ipython-input-129-47fdb4d8fdf7>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  randomfor_model.fit(train_inputs,train_targets)


RandomForestRegressor(max_depth=10, n_jobs=-1, random_state=42)

In [130]:
evaluate(randomfor_model)

(3.5602071617098,
 4.150282269442736,
 array([7.99128706, 6.48981556, 9.07339672, ..., 6.41863548, 8.08693132,
        6.92386098]),
 array([ 5.38115646, 13.50792636, 29.38710439, ..., 39.26905543,
        15.36998618, 16.23239529]))

In [131]:
predict_and_submit(randomfor_model,test_inputs,'random_model_submission.csv')

key  fare_amount
0     2015-01-27 13:08:24.0000002     9.686809
1     2015-01-27 13:08:24.0000003    10.614177
2     2011-10-08 11:53:44.0000002     5.009783
3     2012-12-01 21:12:12.0000002     8.486852
4     2012-12-01 21:12:12.0000003    15.272647
...                           ...          ...
9909  2015-05-10 12:37:51.0000002     8.975906
9910  2015-01-12 17:05:51.0000001    13.436910
9911  2015-04-19 20:44:15.0000001    55.568954
9912  2015-01-31 01:05:19.0000005    21.901466
9913  2015-01-18 14:06:23.0000006     7.681771

[9914 rows x 2 columns]

# Gradient Boosting

In [132]:
from xgboost import XGBRFRegressor

In [133]:
grad_model = XGBRFRegressor(max_depth = 5,objective = 'reg:squarederror',n_estimators =200, random_state = 42,n_jobs = -1)

In [134]:
grad_model.fit(train_inputs,train_targets)

XGBRFRegressor(base_score=0.5, booster='gbtree', callbacks=None,
               colsample_bylevel=1, colsample_bytree=1,
               early_stopping_rounds=None, enable_categorical=False,
               eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
               importance_type=None, interaction_constraints='', max_bin=256,
               max_cat_to_onehot=4, max_delta_step=0, max_depth=5, max_leaves=0,
               min_child_weight=1, missing=nan, monotone_constraints='()',
               n_estimators=200, n_jobs=-1, num_parallel_tree=200,
               objective='reg:squarederror', predictor='auto', random_state=42,
               reg_alpha=0, sampling_method='uniform', scale_pos_weight=1, ...)

In [135]:
evaluate(grad_model)

(4.381207803290297,
 4.486624056103613,
 array([8.11379  , 6.1973367, 9.227623 , ..., 6.200217 , 8.16147  ,
        6.208863 ], dtype=float32),
 array([ 6.200217, 13.221382, 27.353092, ..., 34.70356 , 14.963135,
        13.967027], dtype=float32))

In [136]:
predict_and_submit(grad_model,test_inputs,'grad_model_submission.csv')

key  fare_amount
0     2015-01-27 13:08:24.0000002     9.281945
1     2015-01-27 13:08:24.0000003     9.870304
2     2011-10-08 11:53:44.0000002     6.182840
3     2012-12-01 21:12:12.0000002     8.113790
4     2012-12-01 21:12:12.0000003    14.575932
...                           ...          ...
9909  2015-05-10 12:37:51.0000002     9.249717
9910  2015-01-12 17:05:51.0000001    13.160548
9911  2015-04-19 20:44:15.0000001    54.622227
9912  2015-01-31 01:05:19.0000005    23.718388
9913  2015-01-18 14:06:23.0000006     6.214715

[9914 rows x 2 columns]

# Tuning Hyperparameters

In [137]:
# other_params = {
#     'base_score':[0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8],
#     'colsample_bytree':[0,1],
#     'gamma':[0,1,2,3,4],
#     'max_depth':[2,3,4,5,6,7], 
#     'max_leaves':[0,1,2,3,4,5,6],
#     'min_child_weight':[0,1,2,3,4,5], 
#     'num_parallel_tree':[100, 130, 160, 190, 220, 250, 280], 
# }

In [138]:
def test_params(Model,**params):
    model = Model(**params).fit(train_inputs,train_targets)
    train_rmse = mean_squared_error(model.predict(train_inputs),train_targets,squared=False)
    val_rmse = mean_squared_error(model.predict(val_inputs),val_targets,squared=False)
    return train_rmse,val_rmse

In [139]:
def test_params_and_plot(Model,param_name,param_values,**other_params):
    train_errors,val_errors =[],[]
    for value in param_values:
        params = dict(other_params)
        params[param_name]=value
        train_rmse,val_rmse = test_params(Model,**params)
        train_errors.append(train_rmse)
        val_errors.append(val_rmse)
    plt.figure(figsize=(10,6))
    plt.plot(param_values,train_errors,'b-o')
    plt.plot(param_values,val_errors,'r-o')
    plt.xlabel(param_name)
    plt.ylabel('RMSE')
    

In [140]:
1+1

2

In [141]:
best_params={
    'n_jobs':-1,
    'booster':'gbtree',
    'early_stopping_rounds':None, 
    'enable_categorical':False,
    'objective':'reg:squarederror', 
    'predictor':'auto', 
    'random_state':42,
    'grow_policy':'depthwise',
    'importance_type':None,
    'sampling_method':'uniform',
    'n_estimators':280,
    'max_depth':9,
    'gamma':0,
    'max_leaves':0,
    'num_parallel_tree':100
}

In [144]:
model = XGBRFRegressor(**best_params).fit(train_inputs,train_targets)
train_pred = model.predict(train_inputs)
train_rmse = mean_squared_error(train_targets,train_pred,squared=False)
val_pred = model.predict(val_inputs)
val_rmse = mean_squared_error(val_targets,val_pred,squared=False)
print(train_rmse, val_rmse)

3.638840887946202 4.156041608909352


# using pickle

In [ ]:
import pickle

In [145]:
pickle_out = open('classifier_final.pkl','wb')

In [147]:
pickle.dump(model,pickle_out)

<IPython.core.display.Javascript object>

In [148]:
pickle_out.close()